apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myportal
  name: myportal
spec:
  volumes:
  - name: dipvol   #created socket type volume on minion node3
    hostPath:
     path: /var/run/docker.sock   #docker socket of minion 
     type: Socket
  nodeName:
  containers:
  - image: portainer/portainer
    name: myportal
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: dipvol
      mountPath: /var/run/docker.sock
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
