apiVersion: v1
kind: Pod
metadata: 
 name: dippodenv1
 labels:
  x: helloenv

spec:
 containers:
 - name: dipc111
   image: dockerashu/ckad:v2
   ports:
   - containerPort: 80
   env:         #this is for replacing environment variable in POD
   - name: color # this must be the same variable that we define in dockerfile under ENV key
     value: yellow # this is replaced value

           
